TYPE = CSV
INPUT = {INFILE}
OUTPUT = {TABLENAME}
LOGFILE = {LOGFILE}
BADFILE = {BADFILE}
PARSE_BADFILE = {PARSE_BADFILE}
DUPLICATE_BADFILE = {DUPLICATE_BADFILE}

DELIMITER = |
QUOTE = "
ESCAPE = "
NULL = 

FILTER = fn_tbfundmergercontrol_filter
